### PR TITLE
Update about.markdown

### PR DESCRIPTION
**Pull request by vdumoulin**

### CODE REVIEW

**Comment by vdumoulin** [comment]
@fabianp I found photos for everyone else but Kairan.

**Comment by fabianp** [comment]
amazing, thanks! can you push or make a pull request with those changes (without Kairan)?

**Comment by fabianp** [comment]
@kairan24 : can you add a picture of yourself for the webpage (see above for context)

**Review by fabianp — APPROVED** [review]

**Comment by fabianp** [comment]
> amazing, thanks! can you push or make a pull request with those changes (without Kairan)?

sorry I'm dense, these are the changes

**Comment by fabianp** [comment]
merged!

**Pull request merged**
